---
# tasks file for apacheconfig


- name: httpdconfiguration
  package:
       name: "{{ package_name }}"
       state: present
- name: install git
  package:
          name: "git"
          state: present
- name: start httpd
  service:
          name: "{{ package_name }}"
          state: started
          enabled: yes
- name: copy github code
  git:
          repo: "{{ git_repo }}"
          clone: yes
          dest: "{{ website }}"
