---
# tasks file for ec2oslaunch
- name: OS provisioning
  ec2:
    key_name: "key1a"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ ami_id }}"
    instance_tags:
              Name: "{{ aws_instance_tags }}"
    wait: yes
    count: 1
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    state: present
    region: "{{ aws_region }}"
    group_id: "{{ security_group_id }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
